spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/crocDb
    username: postgres
    password: "postgres"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
server:
  port : 46901
